version: 2.1
orbs:
  docker: circleci/docker@1.0.0
workflows:
  build-deploy:
    jobs:
      - docker/publish:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: 'latest'
      - deploy-to-heroku:
          requires:
            - docker/publish
jobs:
  deploy-to-heroku:
    machine: true
    steps: 
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            heroku container:login
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            docker build -t registry.heroku.com/$HEROKU_APP_NAME/web .
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
            heroku container:release web

