version: 2.1
orbs:
  docker: circleci/docker@1.0.0
jobs:
  deploy-to-heroku:
    steps:
      - run:
          name: Push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            heroku container:login
            heroku container:push web
            heroku container:release web

workflows:
  deploy:
    jobs:
      - docker/publish:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: 'latest'
      - deploy-to-heroku
